# Review

We are using 
- Anaconda, JupyterLab, Julia in Jupyter notebooks, GitHub

Julia is similar to most procedural languages. Julia has easily installed extensions
which provide access to a broad range of scientific libraries with minimal overhead.
Serious attention has been paid to performance. Julia claims and actually seems to be 
performant. 
  
# Cells
Jupyter notebooks contain **Markdown** cells for text and **code** cells for computation. The cheatsheet
-https://www.markdownguide.org/cheat-sheet/
describes the most useful general Markdown commands. For math folks one of the most useful things is that you can just put LaTeX into a markdown cell
$$\int_0^{e^x} \cos(x) dx$$

# Basic Julia
Julia is really pretty easy to read.  We all know writing code is different from reading code. Different
backgrounds give different hurdles. Typing code in a Markdown cell is crazy! Julia prints last code cell 
entries by default.

## Vectors and Arrays
To a computer vectors and arrays are just
efficiently stored blocks of identically typed numbers.

In [19]:
v = [1.2 2.3 3.4] 

1×3 Array{Float64,2}:
 1.2  2.3  3.4

In [34]:
A = [1.2 2.3 3.4; 4.5 5.6 6.7]

2×3 Array{Float64,2}:
 1.2  2.3  3.4
 4.5  5.6  6.7

In [35]:
println(v[1:2])
println(A[1:2,2:3])

[1.2, 2.3]
[2.3 3.4; 5.6 6.7]


## Tuples and Test Matrices
Julia also has a mechanism for lumping entries of possibly different tyoes together.  
It is called a tuple in the documentation. Tuples are used to return more than one thing from functions.     

In [36]:
(m,n)=(3, 4)
A0 = zeros(m,n) #Creates a zero m by n array
Ar = rand(m,n)  #Creates a random m by n array

3×4 Array{Float64,2}:
 0.891609  0.647941  0.47254      0.824899
 0.123265  0.339163  0.000905163  0.949515
 0.52393   0.403325  0.154505     0.257742

## Copying Data
Like C Julia uses pointers to minimize copying large data. 
- You need to explicitly copy data if you want a copy! 
This behavior is familiar if you have written efficient C code. It can produce confusing results if you have not!   

In [45]:
(m,n)=(2,3); A = rand(m,n)
B = copy(A)
B[1,3]*=0.0;
[A; B]

4×3 Array{Float64,2}:
 0.684166  0.0291497  0.226385
 0.991889  0.800852   0.788421
 0.684166  0.0291497  0.0     
 0.991889  0.800852   0.788421

In [46]:
(m,n)=(2,3); A = rand(m,n)
B = A
B[1,3]*=0.0;
[A B]

2×6 Array{Float64,2}:
 0.968977  0.53034   0.0       0.968977  0.53034   0.0     
 0.341659  0.475716  0.970017  0.341659  0.475716  0.970017

## Identity Matrices and Initializing Arrays
In context, Julia interprets I as an appropriately sized indentity matrix. Without context you need to provide a some type information and a dimension! 

In [58]:
m = 4; A=rand(m,m)
A += 12.3*I;
display(A)
Id =  Matrix(1.0*I, 4, 4)

4×4 Array{Float64,2}:
 12.7394     0.30273    0.473225   0.0818769
  0.134974  12.5131     0.118042   0.815074 
  0.63407    0.969452  12.734      0.814886 
  0.613409   0.497842   0.330003  12.695    

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

## Matrix Arithmetic
Matrix and matrix vector muliplication is simple.

In [62]:
(m, n, n1) = (4,3,5)
A=rand(m,n1); B = rand(n1,n); v = rand(n)
display(A*B)
display(B*v)

4×3 Array{Float64,2}:
 1.82917   1.52878  1.3649  
 1.64565   1.39906  1.45613 
 0.866397  1.19391  0.735889
 1.39404   1.6151   1.10494 

5-element Array{Float64,1}:
 0.6032002309199243
 1.4134397457894954
 1.8374623013056268
 0.305439623757055 
 0.9267064721102156

## For Loops
Julia has a standard menagerie of loop constructs.  For now we are going to keep it simple and use a for loop to implement matrix vector multiplication. I timed both versions of the code to make the point that reinventing the wheel is not a good plan.  We need to load the standard LinearAlgebra package to use norm.

In [2]:
using LinearAlgebra
(m, n) = (256,512); A=rand(m,n); v = rand(n)
Av = zeros(m)
@time for i in 1:m
    for j in 1:n 
        Av[i]+=A[i,j]*v[j]
    end
end
@time A*v
norm(Av-A*v)

  0.034429 seconds (787.46 k allocations: 14.023 MiB, 10.79% gc time)
  0.000100 seconds (5 allocations: 2.281 KiB)


1.323365578039422e-12

## Structures 
The eigen command is also in the LinearAlgebra package.  I put it in the cell to remind me: you only need to load packages once in each session.
The ouput says the command has returned a structure (that I have called LambdaV) containing
- A complex m vector containing the eigenvalues
- A complex m by m array containing the eigenvectors (as columns) in the same order

In [22]:
using LinearAlgebra
m = 5; A = rand(m,m)
LambdaV = eigen(A)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
eigenvalues:
5-element Array{Complex{Float64},1}:
    2.535322055330046 + 0.0im                
   0.4231690021943887 + 0.0im                
 -0.40403037445670664 + 0.0im                
 -0.19552699997104145 + 0.43857649873613924im
 -0.19552699997104145 - 0.43857649873613924im
eigenvectors:
5×5 Array{Complex{Float64},2}:
 0.407265+0.0im   0.506275+0.0im  -0.661733+0.0im  …  -0.371626+0.145917im 
 0.412724+0.0im  -0.700031+0.0im  -0.260991+0.0im     -0.386871+0.293647im 
 0.362294+0.0im   0.385524+0.0im   0.543615+0.0im      0.247067+0.0746875im
 0.373384+0.0im   0.187489+0.0im   0.442398+0.0im      0.586187-0.0im      
 0.626993+0.0im  -0.264311+0.0im  0.0525364+0.0im     0.0521572-0.437892im 

## Structure Accessors
Structure **dot accessors** give the pieces of a structure. The accessors here are values and vectors and the : gives the entire column.

In [23]:
using LinearAlgebra
m = 25; A = rand(m,m); LambdaV = eigen(A)
(Lambda,V) = (LambdaV.values, LambdaV.vectors) 
i=3; v = V[:,i]
norm(A*v - Lambda[i]*v)

7.38907332894677e-15

## Sparse PDE Matrices
A sparse matrix is filled almost entirely with zeros.

Large, square, sparse matrices are generated by almost all Partial Differential Equation (PDE) discretization techniques. It is not uncommon for a PDE discretization to have millions of Degrees Of Freedom (DOF) with only very limited local interactions between a few dozen neighboring DOFs. 

The square matrix from such a discretization could easily have size $m = 5 \times 10^6$ with an average of only $36$ non zeros per row. Such a matrix would be $100 36/(5\times 10^6) \approx 0.00072%$ non zeros. Refining a mesh generates more DOFs without changing the number of neighbors. 
- For 2D problems halfing the discretization length increases the number of DOFs by $2^2$: The non-zero density would be a quarter of the original density.  
- For 3D problems halfing the discretization length increases the number of DOFs by $2^3$: The non-zero density would be an eigth of the original density.  

Such sparse PDE matrices $A$ are going to be the primary focus of the course. 
- We are interested in solving linear equations $A.x=b$.
- We are interested in computing a few eigenvalues and eigenvectors of $A$. 
Typically we are interested in a few physically relevant eigenvalues.

Clearly it would be insane to explicitly store all the zero entries. We are going to find out how to find Sparse PDE test matrices and look at the most common transfer format. Then we are going to look at the implementations of 
storage formats and start thinking about computing efficiently with sparse matrices.  

In [3]:
100*36/(5*10^6)

0.00072